#!/usr/bin/env python3
"""Create and schedule safe Garmin training workouts.

The commands in this module are intentionally conservative for agent use:
write operations are dry-run by default and require ``--apply`` before calling
Garmin Connect.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Any

from export_garmin_data import (
    DEFAULT_TOKENSTORE,
    ExportError,
    login_client,
    parse_date,
)
from garmin_storage import WORKOUT_SYNC_STATE_PATH, read_json, write_json
from garminconnect import (
    GarminConnectAuthenticationError,
    GarminConnectConnectionError,
    GarminConnectTooManyRequestsError,
)


SPORT_CYCLING = {"sportTypeId": 2, "sportTypeKey": "cycling", "displayOrder": 2}
NO_TARGET = {
    "workoutTargetTypeId": 1,
    "workoutTargetTypeKey": "no.target",
    "displayOrder": 1,
}

STEP_TYPES = {
    "warmup": {"stepTypeId": 1, "stepTypeKey": "warmup", "displayOrder": 1},
    "cooldown": {"stepTypeId": 2, "stepTypeKey": "cooldown", "displayOrder": 2},
    "interval": {"stepTypeId": 3, "stepTypeKey": "interval", "displayOrder": 3},
    "recovery": {"stepTypeId": 4, "stepTypeKey": "recovery", "displayOrder": 4},
}

TIME_CONDITION = {
    "conditionTypeId": 2,
    "conditionTypeKey": "time",
    "displayOrder": 2,
    "displayable": True,
}


class TrainingCommandError(RuntimeError):
    """Raised when a training command cannot complete safely."""


def workout_hash(workout: dict[str, Any]) -> str:
    payload = json.dumps(workout, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def print_json(payload: Any) -> None:
    print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))


def duration_step(step_type: str, duration_seconds: int, step_order: int) -> dict[str, Any]:
    if duration_seconds <= 0:
        raise TrainingCommandError("step duration must be positive")
    if step_type not in STEP_TYPES:
        raise TrainingCommandError(f"unsupported step type: {step_type}")
    return {
        "type": "ExecutableStepDTO",
        "stepOrder": step_order,
        "stepType": STEP_TYPES[step_type],
        "endCondition": TIME_CONDITION,
        "endConditionValue": float(duration_seconds),
        "targetType": NO_TARGET,
    }


def build_cycling_workout(name: str, steps: list[dict[str, Any]]) -> dict[str, Any]:
    if not name.strip():
        raise TrainingCommandError("workout name cannot be empty")
    if not steps:
        raise TrainingCommandError("workout must include at least one step")

    estimated_duration = int(
        sum(float(step.get("endConditionValue") or 0) for step in steps)
    )
    return {
        "workoutName": name.strip(),
        "sportType": SPORT_CYCLING,
        "estimatedDurationInSecs": estimated_duration,
        "description": "Generated by garmin-rf. Dry-run first; apply only after review.",
        "workoutSegments": [
            {
                "segmentOrder": 1,
                "sportType": SPORT_CYCLING,
                "workoutSteps": steps,
            }
        ],
    }


def build_test_workout(name: str = "RF Test Easy 10m") -> dict[str, Any]:
    return build_cycling_workout(
        name,
        [
            duration_step("warmup", 2 * 60, 1),
            duration_step("interval", 6 * 60, 2),
            duration_step("cooldown", 2 * 60, 3),
        ],
    )


def load_workout_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise TrainingCommandError(f"invalid workout JSON at {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise TrainingCommandError("workout JSON must be an object")
    validate_workout_payload(payload)
    return payload


def validate_workout_payload(payload: dict[str, Any]) -> None:
    if not payload.get("workoutName"):
        raise TrainingCommandError("workout JSON must include workoutName")
    if not isinstance(payload.get("sportType"), dict):
        raise TrainingCommandError("workout JSON must include sportType")
    segments = payload.get("workoutSegments")
    if not isinstance(segments, list) or not segments:
        raise TrainingCommandError("workout JSON must include workoutSegments")


def parse_month(value: str) -> tuple[int, int]:
    try:
        parsed = datetime.strptime(value, "%Y-%m")
    except ValueError as exc:
        raise argparse.ArgumentTypeError("month must use YYYY-MM") from exc
    return parsed.year, parsed.month


def find_first_id(payload: Any, keys: set[str]) -> str | None:
    if isinstance(payload, dict):
        for key, value in payload.items():
            if key in keys and isinstance(value, int | str):
                return str(value)
        for value in payload.values():
            found = find_first_id(value, keys)
            if found:
                return found
    elif isinstance(payload, list):
        for item in payload:
            found = find_first_id(item, keys)
            if found:
                return found
    return None


def planned_actions(workout: dict[str, Any], target_date: date) -> list[dict[str, Any]]:
    return [
        {
            "action": "upload_workout",
            "workout_name": workout["workoutName"],
            "sport": workout.get("sportType", {}).get("sportTypeKey", "unknown"),
        },
        {
            "action": "schedule_workout",
            "date": target_date.isoformat(),
        },
    ]


def record_sync(
    *,
    workout: dict[str, Any],
    target_date: date,
    source_file: str,
    upload_response: dict[str, Any],
    schedule_response: dict[str, Any],
    workout_id: str,
    scheduled_workout_id: str | None,
) -> None:
    state = read_json(
        WORKOUT_SYNC_STATE_PATH,
        default={"version": 1, "workouts": []},
    )
    if not isinstance(state, dict):
        state = {"version": 1, "workouts": []}
    workouts = state.setdefault("workouts", [])
    if not isinstance(workouts, list):
        workouts = []
        state["workouts"] = workouts

    now = datetime.now().isoformat(timespec="seconds")
    workouts.append(
        {
            "source_file": source_file,
            "source_hash": workout_hash(workout),
            "workout_name": workout["workoutName"],
            "garmin_workout_template_id": workout_id,
            "garmin_scheduled_workout_id": scheduled_workout_id,
            "scheduled_date": target_date.isoformat(),
            "last_sync_timestamp": now,
            "last_sync_status": "scheduled",
            "upload_response": upload_response,
            "schedule_response": schedule_response,
        }
    )
    state["last_updated_at"] = now
    write_json(WORKOUT_SYNC_STATE_PATH, state)


def push_workout(
    *,
    workout: dict[str, Any],
    target_date: date,
    tokenstore: Path,
    apply: bool,
    source_file: str,
) -> int:
    validate_workout_payload(workout)
    plan = planned_actions(workout, target_date)

    if not apply:
        print("Dry run only. Re-run with --apply to upload and schedule in Garmin.")
        print_json(
            {
                "mode": "dry_run",
                "planned_actions": plan,
                "source_file": source_file,
                "source_hash": workout_hash(workout),
                "workout": workout,
            }
        )
        return 0

    client = login_client(tokenstore, allow_prompt=False)
    upload_response = client.upload_workout(workout)
    workout_id = find_first_id(
        upload_response,
        {"workoutId", "workout_id", "workoutTemplateId", "id"},
    )
    if not workout_id:
        raise TrainingCommandError(
            "Garmin upload returned no workout id; schedule step was not run. "
            "Inspect the upload response printed below."
        )

    schedule_response = client.schedule_workout(workout_id, target_date.isoformat())
    scheduled_workout_id = find_first_id(
        schedule_response,
        {"scheduledWorkoutId", "scheduled_workout_id", "scheduleId", "id"},
    )
    record_sync(
        workout=workout,
        target_date=target_date,
        source_file=source_file,
        upload_response=upload_response,
        schedule_response=schedule_response,
        workout_id=workout_id,
        scheduled_workout_id=scheduled_workout_id,
    )
    print_json(
        {
            "mode": "applied",
            "planned_actions": plan,
            "workout_id": workout_id,
            "scheduled_workout_id": scheduled_workout_id,
            "sync_state": str(WORKOUT_SYNC_STATE_PATH),
        }
    )
    return 0


def command_build_test_workout(args: argparse.Namespace) -> int:
    workout = build_test_workout(args.name)
    if args.output:
        write_json(args.output, workout)
        print(f"Workout JSON written to: {args.output}")
    else:
        print_json(workout)
    return 0


def command_push_workout(args: argparse.Namespace) -> int:
    if args.workout_json:
        workout = load_workout_json(args.workout_json)
        source_file = str(args.workout_json)
    else:
        workout = build_test_workout(args.name)
        source_file = "generated:RF Test Easy 10m"

    return push_workout(
        workout=workout,
        target_date=args.date,
        tokenstore=args.tokenstore,
        apply=args.apply,
        source_file=source_file,
    )


def command_list_workouts(args: argparse.Namespace) -> int:
    client = login_client(args.tokenstore, allow_prompt=False)
    print_json(client.get_workouts(start=args.start, limit=args.limit))
    return 0


def command_list_scheduled(args: argparse.Namespace) -> int:
    client = login_client(args.tokenstore, allow_prompt=False)
    year, month = args.month
    print_json(client.get_scheduled_workouts(year, month))
    return 0


def command_examples(_args: argparse.Namespace) -> int:
    print(
        """# Garmin RF command examples

Build the harmless test workout JSON:

```powershell
poetry run garmin-rf build-test-workout
```

Dry-run upload and scheduling for one manually chosen date:

```powershell
poetry run garmin-rf push-workout --date 2026-06-18 --dry-run
```

Apply the same workout only after reviewing the dry-run payload:

```powershell
poetry run garmin-rf push-workout --date 2026-06-18 --apply
```

Push an LLM-generated workout JSON file:

```powershell
poetry run garmin-rf push-workout --date 2026-06-18 --workout-json derived/ridefaster/rf_easy_10m.json --dry-run
poetry run garmin-rf push-workout --date 2026-06-18 --workout-json derived/ridefaster/rf_easy_10m.json --apply
```

Inspect Garmin workout library and calendar state:

```powershell
poetry run garmin-rf list-workouts --limit 25
poetry run garmin-rf list-scheduled --month 2026-06
```
"""
    )
    return 0


def add_apply_flags(parser: argparse.ArgumentParser) -> None:
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--dry-run",
        dest="apply",
        action="store_false",
        default=False,
        help="Print planned Garmin actions without writing. This is the default.",
    )
    mode.add_argument(
        "--apply",
        action="store_true",
        help="Upload and schedule the workout in Garmin Connect.",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Create and schedule Garmin cycling training workouts safely."
    )
    parser.add_argument(
        "--tokenstore",
        type=Path,
        default=DEFAULT_TOKENSTORE,
        help="Garmin token directory outside the repository.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_test = subparsers.add_parser(
        "build-test-workout",
        help="Print or write the harmless RF Test Easy 10m workout JSON.",
    )
    build_test.add_argument("--name", default="RF Test Easy 10m")
    build_test.add_argument("--output", type=Path)
    build_test.set_defaults(func=command_build_test_workout)

    push = subparsers.add_parser(
        "push-workout",
        help="Dry-run or apply upload/schedule for a workout JSON payload.",
    )
    push.add_argument("--date", type=parse_date, required=True)
    push.add_argument("--name", default="RF Test Easy 10m")
    push.add_argument(
        "--workout-json",
        type=Path,
        help="Path to an LLM-generated Garmin workout JSON file. "
        "If omitted, the harmless test workout is used.",
    )
    add_apply_flags(push)
    push.set_defaults(func=command_push_workout)

    list_workouts = subparsers.add_parser(
        "list-workouts",
        help="List Garmin workout templates. Read-only.",
    )
    list_workouts.add_argument("--start", type=int, default=0)
    list_workouts.add_argument("--limit", type=int, default=25)
    list_workouts.set_defaults(func=command_list_workouts)

    list_scheduled = subparsers.add_parser(
        "list-scheduled",
        help="List scheduled Garmin workouts for a YYYY-MM month. Read-only.",
    )
    list_scheduled.add_argument("--month", type=parse_month, required=True)
    list_scheduled.set_defaults(func=command_list_scheduled)

    examples = subparsers.add_parser(
        "examples",
        help="Print LLM-agent command examples.",
    )
    examples.set_defaults(func=command_examples)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    try:
        return args.func(args)
    except GarminConnectTooManyRequestsError as exc:
        print(f"Garmin rate limit exceeded: {exc}", file=sys.stderr)
        return 2
    except (
        GarminConnectAuthenticationError,
        GarminConnectConnectionError,
        ExportError,
        TrainingCommandError,
        OSError,
        ValueError,
    ) as exc:
        print(str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
